### ISSUE TITLE
Error on reaching the end of the survey/thanks page

### ISSUE THREAD

**Issue by markrian** [StateOfJS/StateOfJS-Vulcan#129]
I just completed the 2021/2022 survey, and reached the thanks page, and got this error in the view:

```
can't access property "find", a is undefined
```

Here's the stack trace logged in the console (though it doesn't look particularly useful :shrug:):

```
TypeError: can't access property "find", a is undefined
    f https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:465
    g https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:465
    Na https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    PB https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    ru https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    tu https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    eu https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    KB https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    go https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    unstable_runWithPriority https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:169
    yo https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    go https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    bo https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    zB https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    ns https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    onNewData https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    bindEnvironment https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:1
f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
```

**Comment by dr-dimitru** [comment]
Same here, see screenshot: ![Screen Shot 2022-01-24 at 3 07 23 PM](https://user-images.githubusercontent.com/1686778/150788325-5d5b8bf9-ac43-4b8e-895c-aa4f8117e301.png)

**Comment by khofaai** [comment]
Same here, on Firefox 96.0, ubuntu 21.04 
![image](https://user-images.githubusercontent.com/12723639/150788607-35ffec30-7054-4724-8abe-d58d4764e2c0.png)

**Comment by edimitchel** [comment]
Seams to be correlated with https://github.com/StateOfJS/StateOfJS-Vulcan/blob/master/packages/stateofjs/lib/components/common/Score.jsx#L20

<img width="376" alt="Capture d’écran 2022-01-24 à 14 24 30" src="https://user-images.githubusercontent.com/2922851/150790722-6d3b13fb-baad-4c90-ac63-10952ca9b729.png">

**Comment by shiftgeist** [comment]
![image](https://user-images.githubusercontent.com/30648730/150806953-4875b598-3d07-464a-9830-8c06cc863281.png)

console:

```
Some cookies are misusing the “SameSite“ attribute, so it won’t work as expected 5
[GraphQL error]: Message: invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0, Location: line 2, col 3, Path: entities f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
Object { stack: "r@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:1:4173\n_livedata_result@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:330:17717\nonMessage@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:330:20028\ne/_launchConnection/this.socket.onmessage/<@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:324:2633\nforEachCallback@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:324:3704\ne/_launchConnection/this.socket.onmessage@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:324:2601\ne/r.prototype.dispatchEvent@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:324:6211\ne/k.prototype._dispatchMessage@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:324:19854\ne/k.prototype._didMessage@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:324:20755\ne/k.websocket/o.ws.onmessage@https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:324:22862\n", isClientSafe: true, error: 403, reason: "Email already exists.", details: undefined, message: "Email already exists. [403]", errorType: "Meteor.Error" }
f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
[GraphQL error]: Message: invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0, Location: line 2, col 3, Path: entities f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
Uncaught (in promise) Error: invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0
    t https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    L https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    n https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    then https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    then https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    c https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    M https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    A https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    e https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    r https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    r https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    next https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:121
    M https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    A https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    e https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    next https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    M https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    A https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    e https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    v https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    bindEnvironment https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:1
f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:136:64209
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o324825.ingest.sentry.io/api/1828516/store/?sentry_key=de63e169faba4cf99f03f255ca4a9266&sentry_version=7. (Reason: CORS request did not succeed). Status code: (null).

[GraphQL error]: Message: invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0, Location: line 2, col 3, Path: entities f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
[GraphQL error]: Message: invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0, Location: line 2, col 3, Path: entities f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
[GraphQL error]: Message: invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0, Location: line 2, col 3, Path: entities 2 f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
TypeError: can't access property "find", a is undefined
    f https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:465
    g https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:465
    Na https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    PB https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    ru https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    tu https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    eu https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    KB https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    go https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    unstable_runWithPriority https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:169
    yo https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    go https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    bo https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    zB https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    ns https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:151
    onNewData https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:136
    bindEnvironment https://app.stateofjs.com/f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js?meteor_js_resource=true:1
f98c5fdc61a4028f265bcc43b87975c1a5be8f76.js:221:157102
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o324825.ingest.sentry.io/api/1828516/store/?sentry_key=de63e169faba4cf99f03f255ca4a9266&sentry_version=7. (Reason: CORS request did not succeed). Status code: (null).
```

**Comment by krnlde** [comment]
Seems to be resolved now.

**Comment by SachaG** [comment]
Really sorry about that, it seems like when the server goes down it triggers all kinds of unrelated issues. Your data should still be saved though.
